// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/_middleware.ts";
import * as $3 from "./routes/account/_middleware.ts";
import * as $4 from "./routes/account/create/[page].tsx";
import * as $5 from "./routes/account/create/index.tsx";
import * as $6 from "./routes/dev/apps/[appId].tsx";
import * as $7 from "./routes/dev/apps/createApp.tsx";
import * as $8 from "./routes/dev/apps/index.tsx";
import * as $9 from "./routes/dev/dashboard.tsx";
import * as $10 from "./routes/dev/index.tsx";
import * as $11 from "./routes/dev/login.tsx";
import * as $12 from "./routes/docs/[...slug].tsx";
import * as $13 from "./routes/docs/out.tsx";
import * as $14 from "./routes/gfm.css.ts";
import * as $15 from "./routes/home.tsx";
import * as $16 from "./routes/index.tsx";
import * as $17 from "./routes/login.tsx";
import * as $18 from "./routes/logout.tsx";
import * as $19 from "./routes/oauth2/auth.tsx";
import * as $20 from "./routes/oauth2/google/callback.tsx";
import * as $21 from "./routes/oauth2/google/index.tsx";
import * as $22 from "./routes/signup.tsx";
import * as $$0 from "./islands/AccountForm.tsx";
import * as $$1 from "./islands/ApplicationForm.tsx";
import * as $$2 from "./islands/Counter.tsx";
import * as $$3 from "./islands/Input.tsx";
import * as $$4 from "./islands/Login.tsx";
import * as $$5 from "./islands/PersonalForm.tsx";
import * as $$6 from "./islands/ProfileNavButton.tsx";
import * as $$7 from "./islands/SearchButton.tsx";
import * as $$8 from "./islands/UserNavbar.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/_middleware.ts": $2,
    "./routes/account/_middleware.ts": $3,
    "./routes/account/create/[page].tsx": $4,
    "./routes/account/create/index.tsx": $5,
    "./routes/dev/apps/[appId].tsx": $6,
    "./routes/dev/apps/createApp.tsx": $7,
    "./routes/dev/apps/index.tsx": $8,
    "./routes/dev/dashboard.tsx": $9,
    "./routes/dev/index.tsx": $10,
    "./routes/dev/login.tsx": $11,
    "./routes/docs/[...slug].tsx": $12,
    "./routes/docs/out.tsx": $13,
    "./routes/gfm.css.ts": $14,
    "./routes/home.tsx": $15,
    "./routes/index.tsx": $16,
    "./routes/login.tsx": $17,
    "./routes/logout.tsx": $18,
    "./routes/oauth2/auth.tsx": $19,
    "./routes/oauth2/google/callback.tsx": $20,
    "./routes/oauth2/google/index.tsx": $21,
    "./routes/signup.tsx": $22,
  },
  islands: {
    "./islands/AccountForm.tsx": $$0,
    "./islands/ApplicationForm.tsx": $$1,
    "./islands/Counter.tsx": $$2,
    "./islands/Input.tsx": $$3,
    "./islands/Login.tsx": $$4,
    "./islands/PersonalForm.tsx": $$5,
    "./islands/ProfileNavButton.tsx": $$6,
    "./islands/SearchButton.tsx": $$7,
    "./islands/UserNavbar.tsx": $$8,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
